In [1]:
import torch

In [2]:
torch.__version__

'2.6.0+cu124'

In [5]:
import transformers
from transformers import AutoTokenizer

In [6]:
 tokenizer = AutoTokenizer.from_pretrained("gpt2")

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [36]:
sentence = "I skip across the"

In [37]:
input_ids = tokenizer(sentence,return_tensors='pt').input_ids

In [38]:
input_ids

tensor([[   40, 14267,  1973,   262]])

In [39]:
tokenizer.decode(37534)

'Prep'

In [40]:
for token_id in input_ids[0]:
    print(tokenizer.decode(token_id))

I
 skip
 across
 the


In [41]:
from transformers import AutoModelForCausalLM

In [42]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

In [43]:
outputs = gpt2(input_ids)

In [44]:
outputs.logits

tensor([[[-39.3084, -39.0100, -41.8374,  ..., -46.9337, -44.9074, -39.5149],
         [-78.0579, -78.4766, -82.9907,  ..., -87.3913, -86.9834, -79.6007],
         [-73.0664, -74.0119, -78.5556,  ..., -81.0934, -82.5249, -75.8570],
         [-87.5486, -86.0567, -88.3320,  ..., -88.2509, -90.5480, -86.1209]]],
       grad_fn=<UnsafeViewBackward0>)

In [45]:
final_logits = gpt2(input_ids).logits[0,-1]

In [46]:
final_logits

tensor([-87.5486, -86.0567, -88.3320,  ..., -88.2509, -90.5480, -86.1209],
       grad_fn=<SelectBackward0>)

In [47]:
final_logits.argmax()

tensor(1627)

In [48]:
tokenizer.decode(final_logits.argmax())

' line'