In [2]:
import torch
from torch import nn
from torch.nn import functional as F

In [3]:
import numpy as np
import matplotlib.pyplot as plt


In [4]:
with open(('../pytorch-for-deep-learning/Data/shakespeare.txt'), 'r', encoding='utf-8') as f:
    text = f.read()
print('Length of dataset in characters:', len(text))

Length of dataset in characters: 5445609


In [5]:
print('First 1000 characters:\n', text[:1000])

First 1000 characters:
 
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say 

In [6]:
all_characters = set(text)
print('All characters:', all_characters)

All characters: {'(', 'v', ']', '6', 'f', '2', 'Y', '-', 'e', 'd', ';', ',', 'K', '4', ' ', 'h', 'o', 'H', 'U', 'N', 'a', '<', 'r', 'b', 'z', '0', 'O', 'j', 'T', 'C', 'u', 'g', 'k', 'V', '9', 't', 'n', 'R', '8', '"', 'I', 'c', '1', 'p', 'F', "'", 'w', '3', '[', 'W', 'q', '`', 'A', 'S', 'y', '>', 'L', '&', 'G', 'm', 'Z', 's', '.', 'J', 'P', 'E', 'B', 'x', '!', 'Q', 'l', '\n', '5', '|', 'M', 'X', '7', '}', 'i', '_', ')', ':', 'D', '?'}


In [7]:
decoder = dict(enumerate(all_characters))

In [8]:
decoder

{0: '(',
 1: 'v',
 2: ']',
 3: '6',
 4: 'f',
 5: '2',
 6: 'Y',
 7: '-',
 8: 'e',
 9: 'd',
 10: ';',
 11: ',',
 12: 'K',
 13: '4',
 14: ' ',
 15: 'h',
 16: 'o',
 17: 'H',
 18: 'U',
 19: 'N',
 20: 'a',
 21: '<',
 22: 'r',
 23: 'b',
 24: 'z',
 25: '0',
 26: 'O',
 27: 'j',
 28: 'T',
 29: 'C',
 30: 'u',
 31: 'g',
 32: 'k',
 33: 'V',
 34: '9',
 35: 't',
 36: 'n',
 37: 'R',
 38: '8',
 39: '"',
 40: 'I',
 41: 'c',
 42: '1',
 43: 'p',
 44: 'F',
 45: "'",
 46: 'w',
 47: '3',
 48: '[',
 49: 'W',
 50: 'q',
 51: '`',
 52: 'A',
 53: 'S',
 54: 'y',
 55: '>',
 56: 'L',
 57: '&',
 58: 'G',
 59: 'm',
 60: 'Z',
 61: 's',
 62: '.',
 63: 'J',
 64: 'P',
 65: 'E',
 66: 'B',
 67: 'x',
 68: '!',
 69: 'Q',
 70: 'l',
 71: '\n',
 72: '5',
 73: '|',
 74: 'M',
 75: 'X',
 76: '7',
 77: '}',
 78: 'i',
 79: '_',
 80: ')',
 81: ':',
 82: 'D',
 83: '?'}

In [9]:
encoder = {v: k for k, v in decoder.items()}
encoder

{'(': 0,
 'v': 1,
 ']': 2,
 '6': 3,
 'f': 4,
 '2': 5,
 'Y': 6,
 '-': 7,
 'e': 8,
 'd': 9,
 ';': 10,
 ',': 11,
 'K': 12,
 '4': 13,
 ' ': 14,
 'h': 15,
 'o': 16,
 'H': 17,
 'U': 18,
 'N': 19,
 'a': 20,
 '<': 21,
 'r': 22,
 'b': 23,
 'z': 24,
 '0': 25,
 'O': 26,
 'j': 27,
 'T': 28,
 'C': 29,
 'u': 30,
 'g': 31,
 'k': 32,
 'V': 33,
 '9': 34,
 't': 35,
 'n': 36,
 'R': 37,
 '8': 38,
 '"': 39,
 'I': 40,
 'c': 41,
 '1': 42,
 'p': 43,
 'F': 44,
 "'": 45,
 'w': 46,
 '3': 47,
 '[': 48,
 'W': 49,
 'q': 50,
 '`': 51,
 'A': 52,
 'S': 53,
 'y': 54,
 '>': 55,
 'L': 56,
 '&': 57,
 'G': 58,
 'm': 59,
 'Z': 60,
 's': 61,
 '.': 62,
 'J': 63,
 'P': 64,
 'E': 65,
 'B': 66,
 'x': 67,
 '!': 68,
 'Q': 69,
 'l': 70,
 '\n': 71,
 '5': 72,
 '|': 73,
 'M': 74,
 'X': 75,
 '7': 76,
 '}': 77,
 'i': 78,
 '_': 79,
 ')': 80,
 ':': 81,
 'D': 82,
 '?': 83}

In [10]:
encoded_text = np.array([encoder[c] for c in text], dtype=np.int32)
encoded_text[:1000]


array([71, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 42, 71, 14, 14, 44, 22, 16, 59, 14,  4, 20, 78,
       22,  8, 61, 35, 14, 41, 22,  8, 20, 35, 30, 22,  8, 61, 14, 46,  8,
       14,  9,  8, 61, 78, 22,  8, 14, 78, 36, 41, 22,  8, 20, 61,  8, 11,
       71, 14, 14, 28, 15, 20, 35, 14, 35, 15,  8, 22,  8, 23, 54, 14, 23,
        8, 20, 30, 35, 54, 45, 61, 14, 22, 16, 61,  8, 14, 59, 78, 31, 15,
       35, 14, 36,  8,  1,  8, 22, 14,  9, 78,  8, 11, 71, 14, 14, 66, 30,
       35, 14, 20, 61, 14, 35, 15,  8, 14, 22, 78, 43,  8, 22, 14, 61, 15,
       16, 30, 70,  9, 14, 23, 54, 14, 35, 78, 59,  8, 14,  9,  8, 41,  8,
       20, 61,  8, 11, 71, 14, 14, 17, 78, 61, 14, 35,  8, 36,  9,  8, 22,
       14, 15,  8, 78, 22, 14, 59, 78, 31, 15, 35, 14, 23,  8, 20, 22, 14,
       15, 78, 61, 14, 59,  8, 59, 16, 22, 54, 81, 71, 14, 14, 66, 30, 35,
       14, 35, 15, 16, 30, 14, 41, 16, 36, 35, 22, 20, 41, 35,  8,  9, 14,
       35, 16, 14, 35, 15

In [11]:
decoder[9] # space

'd'

In [12]:
def one_hot_encoder(encoded_text, num_uni_chars):
    one_hot = np.zeros((len(encoded_text), num_uni_chars), dtype=np.float32)
    one_hot[np.arange(len(encoded_text)), encoded_text] = 1
    return one_hot
num_uni_chars = len(all_characters)
one_hot = one_hot_encoder(encoded_text, num_uni_chars)
print('One-hot shape:', one_hot.shape)

One-hot shape: (5445609, 84)


In [13]:
arr = np.array([1,2,0])
arr

array([1, 2, 0])

In [14]:
one_hot_encoder(arr, 3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [15]:
example_text = np.arange(10)
example_text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
example_text.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    # X : encoded text of length seq_len
    # Y : encoded text shifted by one

    char_per_batch = samp_per_batch * seq_len
    num_batches = len(encoded_text) // char_per_batch
    encoded_text = encoded_text[:num_batches * char_per_batch]
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    for n in range(0, encoded_text.shape[1], seq_len):
        x = encoded_text[:, n:n + seq_len]
        y = encoded_text[:, n + 1:n + seq_len + 1]
        yield x, y
# Check the function
samp_per_batch = 2
seq_len = 10
x, y = next(generate_batches(encoded_text, samp_per_batch, seq_len))
print('X shape:', x.shape)
print('Y shape:', y.shape)
# Check the first batch
print('X:', x)
print('Y:', y)


X shape: (2, 10)
Y shape: (2, 10)
X: [[71 14 14 14 14 14 14 14 14 14]
 [15  8 14 59 16  1  8 61 71 14]]
Y: [[14 14 14 14 14 14 14 14 14 14]
 [ 8 14 59 16  1  8 61 71 14 14]]
