In [12]:
import torch
from torch import nn
from torch.nn import functional as F

In [13]:
import numpy as np
import matplotlib.pyplot as plt


In [14]:
with open(('../pytorch-for-deep-learning/Data/shakespeare.txt'), 'r', encoding='utf-8') as f:
    text = f.read()
print('Length of dataset in characters:', len(text))

Length of dataset in characters: 5445609


In [15]:
print('First 1000 characters:\n', text[:1000])

First 1000 characters:
 
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say 

In [16]:
all_characters = set(text)
print('All characters:', all_characters)

All characters: {'V', '[', 'J', '\n', '&', '?', '5', 'e', 'u', ' ', 'Y', '-', 'O', '1', '!', '(', '>', 'Q', 'z', 'E', 'L', 'Z', 'C', '_', 'B', 'U', 'y', 'S', 'D', 'c', '3', '4', 'o', 'p', '2', 'x', 'T', 'W', 'A', '9', 'r', 'K', 'N', 'j', ')', 'F', 'k', 'a', 'q', 's', 'f', 'X', ',', 'h', 'm', '7', '|', 'd', 'l', 'R', 'v', "'", '<', 'H', 'P', ']', ':', '}', 't', '8', 'w', 'n', 'b', '6', '"', '`', 'M', ';', 'i', 'g', 'I', 'G', '0', '.'}


In [17]:
decoder = dict(enumerate(all_characters))

In [18]:
decoder

{0: 'V',
 1: '[',
 2: 'J',
 3: '\n',
 4: '&',
 5: '?',
 6: '5',
 7: 'e',
 8: 'u',
 9: ' ',
 10: 'Y',
 11: '-',
 12: 'O',
 13: '1',
 14: '!',
 15: '(',
 16: '>',
 17: 'Q',
 18: 'z',
 19: 'E',
 20: 'L',
 21: 'Z',
 22: 'C',
 23: '_',
 24: 'B',
 25: 'U',
 26: 'y',
 27: 'S',
 28: 'D',
 29: 'c',
 30: '3',
 31: '4',
 32: 'o',
 33: 'p',
 34: '2',
 35: 'x',
 36: 'T',
 37: 'W',
 38: 'A',
 39: '9',
 40: 'r',
 41: 'K',
 42: 'N',
 43: 'j',
 44: ')',
 45: 'F',
 46: 'k',
 47: 'a',
 48: 'q',
 49: 's',
 50: 'f',
 51: 'X',
 52: ',',
 53: 'h',
 54: 'm',
 55: '7',
 56: '|',
 57: 'd',
 58: 'l',
 59: 'R',
 60: 'v',
 61: "'",
 62: '<',
 63: 'H',
 64: 'P',
 65: ']',
 66: ':',
 67: '}',
 68: 't',
 69: '8',
 70: 'w',
 71: 'n',
 72: 'b',
 73: '6',
 74: '"',
 75: '`',
 76: 'M',
 77: ';',
 78: 'i',
 79: 'g',
 80: 'I',
 81: 'G',
 82: '0',
 83: '.'}

In [19]:
encoder = {v: k for k, v in decoder.items()}
encoder

{'V': 0,
 '[': 1,
 'J': 2,
 '\n': 3,
 '&': 4,
 '?': 5,
 '5': 6,
 'e': 7,
 'u': 8,
 ' ': 9,
 'Y': 10,
 '-': 11,
 'O': 12,
 '1': 13,
 '!': 14,
 '(': 15,
 '>': 16,
 'Q': 17,
 'z': 18,
 'E': 19,
 'L': 20,
 'Z': 21,
 'C': 22,
 '_': 23,
 'B': 24,
 'U': 25,
 'y': 26,
 'S': 27,
 'D': 28,
 'c': 29,
 '3': 30,
 '4': 31,
 'o': 32,
 'p': 33,
 '2': 34,
 'x': 35,
 'T': 36,
 'W': 37,
 'A': 38,
 '9': 39,
 'r': 40,
 'K': 41,
 'N': 42,
 'j': 43,
 ')': 44,
 'F': 45,
 'k': 46,
 'a': 47,
 'q': 48,
 's': 49,
 'f': 50,
 'X': 51,
 ',': 52,
 'h': 53,
 'm': 54,
 '7': 55,
 '|': 56,
 'd': 57,
 'l': 58,
 'R': 59,
 'v': 60,
 "'": 61,
 '<': 62,
 'H': 63,
 'P': 64,
 ']': 65,
 ':': 66,
 '}': 67,
 't': 68,
 '8': 69,
 'w': 70,
 'n': 71,
 'b': 72,
 '6': 73,
 '"': 74,
 '`': 75,
 'M': 76,
 ';': 77,
 'i': 78,
 'g': 79,
 'I': 80,
 'G': 81,
 '0': 82,
 '.': 83}

In [20]:
encoded_text = np.array([encoder[c] for c in text], dtype=np.int32)
encoded_text[:1000]


array([ 3,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9, 13,  3,  9,  9, 45, 40, 32, 54,  9, 50, 47, 78,
       40,  7, 49, 68,  9, 29, 40,  7, 47, 68,  8, 40,  7, 49,  9, 70,  7,
        9, 57,  7, 49, 78, 40,  7,  9, 78, 71, 29, 40,  7, 47, 49,  7, 52,
        3,  9,  9, 36, 53, 47, 68,  9, 68, 53,  7, 40,  7, 72, 26,  9, 72,
        7, 47,  8, 68, 26, 61, 49,  9, 40, 32, 49,  7,  9, 54, 78, 79, 53,
       68,  9, 71,  7, 60,  7, 40,  9, 57, 78,  7, 52,  3,  9,  9, 24,  8,
       68,  9, 47, 49,  9, 68, 53,  7,  9, 40, 78, 33,  7, 40,  9, 49, 53,
       32,  8, 58, 57,  9, 72, 26,  9, 68, 78, 54,  7,  9, 57,  7, 29,  7,
       47, 49,  7, 52,  3,  9,  9, 63, 78, 49,  9, 68,  7, 71, 57,  7, 40,
        9, 53,  7, 78, 40,  9, 54, 78, 79, 53, 68,  9, 72,  7, 47, 40,  9,
       53, 78, 49,  9, 54,  7, 54, 32, 40, 26, 66,  3,  9,  9, 24,  8, 68,
        9, 68, 53, 32,  8,  9, 29, 32, 71, 68, 40, 47, 29, 68,  7, 57,  9,
       68, 32,  9, 68, 53

In [22]:
decoder[9] # space

' '

In [23]:
def one_hot_encoder(encoded_text, num_uni_chars):
    one_hot = np.zeros((len(encoded_text), num_uni_chars), dtype=np.float32)
    one_hot[np.arange(len(encoded_text)), encoded_text] = 1
    return one_hot
num_uni_chars = len(all_characters)
one_hot = one_hot_encoder(encoded_text, num_uni_chars)
print('One-hot shape:', one_hot.shape)

One-hot shape: (5445609, 84)


In [25]:
arr = np.array([1,2,0])
arr

array([1, 2, 0])

In [26]:
one_hot_encoder(arr, 3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)